### ISSUE TITLE
When inside an OB issue, provide way to switch language

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#10]
e.g. in 1173, I'd like to switch to see the Russian version (preferably keeping my context [where I was browsing]).

**Comment by strogonoff** [comment]
Language switch will likely be added in the web UI. Scroll position may not be preserved unless there is a valid specific reason why would OB consumer, who presumably has one language of choice, keep switching between versions.

**Comment by ronaldtse** [comment]
That's fine, thanks!

**Comment by strogonoff** [comment]
(Example: https://www.ituob.org/issues/1173-en/)
