### ISSUE TITLE
Required environment variables for GHA workflow appear to be missing

### ISSUE THREAD

**Issue by strogonoff** [ituob/ituob.org#24]
This causes the workflow to fail as follows (in this case S3 bucket name looks not set):

<img width="833" alt="Screenshot 2019-10-31 at 8 13 10 PM" src="https://user-images.githubusercontent.com/292959/67945870-f453e980-fc1a-11e9-9620-02e6e778ccc1.png">

**Comment by strogonoff** [comment]
@ronaldtse ping—if you’re back on your main machine, perhaps you could provide the missing variable(s) for GHA to work. I think it needs `S3_BUCKET_NAME` and `AWS_REGION`

**Comment by ronaldtse** [comment]
Closing, not happening anymore.
