### ISSUE TITLE
Migrate to `main` branch

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#41]

**Comment by strogonoff** [comment]
Uhm… branch change may affect ITU OB editor. I’m not sure it plays well with different branch names. Can push a hotfix perhaps, so that @Darkod55’s work is not blocked.

**Comment by ronaldtse** [comment]
I don't think the OB Editor works with this repo. The data repo branch is unchanged, but we should indeed change it too.

**Comment by strogonoff** [comment]
Right, whew.
