### ISSUE TITLE
Add Google analytics

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#44]
We should apply Google analytics so as to view traffic.

**Comment by ronaldtse** [comment]
Google Analytics tag:

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-L3TCVBGNJ0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-L3TCVBGNJ0');
</script>
```

**Comment by ronaldtse** [comment]
@strogonoff could you please help add this ASAP? Thanks!

**Comment by strogonoff** [comment]
@CAMOBAP could you take a look. You can put GA ID into config or just hardcode in template, it’s not important right now I think because we aren’t going to manage it from environment.

**Comment by ronaldtse** [comment]
This is an urgent issue. @CAMOBAP can you help check? Thanks!

**Comment by CAMOBAP** [comment]
The implementation looks straight forward - https://morotsman.github.io/blog,/google/analytics,/jekyll,/github/pages/2020/07/07/add-google-analytics.html

PR is on the way

**Comment by ronaldtse** [comment]
Google Analytics is working now. Thanks @CAMOBAP !<img width="739" alt="Screenshot 2023-03-23 at 8 40 32 AM" src="https://user-images.githubusercontent.com/11865/227069703-9f637654-af91-402b-a65e-1e41f81b6079.png">
