### ISSUE TITLE
Use Swiss date format

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#9]
Just as shown on the ITU site.

<img width="339" alt="Screen Shot 2019-07-11 at 9 55 54 AM" src="https://user-images.githubusercontent.com/11865/61016405-156da180-a3c2-11e9-9bf4-5d2745ac95a4.png">

**Comment by strogonoff** [comment]
https://github.com/ituob/ituob.org/issues/16

**Comment by ronaldtse** [comment]
“Swiss date”. Nice thanks! :wink:

**Comment by strogonoff** [comment]
I believe it’s used by a few European countries, but since in this case the headquarters are in Geneva I assumed it can be more precisely specified :)
